### PR TITLE
Fixing hardcoded path in FreePackage addresses issue #28

### PR DESCRIPTION
**Pull request by gardner**

### CODE REVIEW

**Comment by patrik111** [comment]
Not sure who this might reach,

But I was wondering when there might be  a new windows release?

When that happens, I am sure there is a crowd looking for this program at
www.boatdesign.net who more than likely would be helpful with user comments.

Specific forum:
https://www.boatdesign.net/forums/design-software/

Kind regards
Patrik

2017-10-12 3:20 GMT+02:00 Gardner Bickford <notifications@github.com>:

**Comment by gardner** [comment]
Doesn't seem to be much activity

**Comment by patrik111** [comment]
Hi,
True that is.
however sometimes when there are new relases there are quite some activity
there.

The downside is that the releases need to be sort of working out of the box
with minimal work (like the windows releases ) for the audience to download
and be running. think anything more demanding on the users than that is
difficult.

I seem to recall that a while back there were a lot of discussions on
Freeship and how to do stuff in it, followed by a period where there were
questions as to where to get hold of it.

Anyways, personally looking forward to next release

thanks


2017-12-17 22:52 GMT+01:00 Gardner Bickford <notifications@github.com>:

**Comment by markmal** [comment]
Hi Gardner, 
thanks for your change. Sorry I did not merge your change into the repo before because I was new to Git. :(

**Comment by gardner** [comment]
No worries! It's never too late to make improvements. 🎉  

Welcome to GitHub!

**Pull request merged**
